version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      #checkoutは、GitHubからCircleCIの環境にソースコードをコピー(git clone)してきます。
      #CircleCIの環境にはGitHubからソースコードをコピーしてきただけなので、LaravelのフレームワークのコードなどPHP関連パッケージが存在しません。
      #CircleCIで実施するテストでは、あなたのPCのローカル環境で実施するテストとは違って、このように必要なパッケージを毎回インストールしなければならない
      - checkout
      #Composerを使用してPHP関連パッケージをインストールします
      - run: composer install -n --prefer-dist
      #PCの開発環境を構築した時と同様に、npmを使用してJavaScript関連パッケージをインストール
      - run: npm ci
      #PCの開発環境を構築した時と同様に、JavaScriptのトランスパイルを行なっています。
      - run: npm run dev

      - run:
        #nameは、CircleCIの画面に表示されるステップ名となります。省略すると、commandの内容がそのままステップ名として表示されます。
        #テストを実行
          name: php test
        #commandには、実行するシェルのコマンドを定義します。
          command: vendor/bin/phpunit